version: '3.8'

services:

  postgres:
    image: postgres:12
    env_file: .env
    ports:
    - ${POSTGRES_PORT}:${POSTGRES_PORT}

  web:
    build: ./app
    container_name: dash_app
    command: python app/app.py
    restart: always
    env_file: .env
    volumes:
      - .:/code/
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  redis:
    image: "redis:alpine"
    env_file: .env

  celery:
    image: celery:latest
    build: ./app
    command: celery -A app.celery worker -l INFO
    env_file: .env
    depends_on:
      - redis
  #   user: nobody

  celery-beat:
    image: celery:latest
    build: ./app
    command: celery -A app.celery beat -l INFO
    env_file: .env
    depends_on:
      - redis

  flower:  
    image: mher/flower:0.9.7
    env_file: .env
    build: ./app
    command: celery -A app.celery --broker=${REDIS_HOST}://${REDIS_HOST} flower
    ports:
      - ${FLOWER_PORT}:${FLOWER_PORT}
    depends_on:
      - redis
      - celery
