"""empty message

Revision ID: 21a8152d4580
Revises: a3305e360b39
Create Date: 2022-02-13 17:48:15.270939

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "21a8152d4580"
down_revision = "a3305e360b39"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "houses", sa.Column("market", sa.Enum("Aftermarket", "Primary market", name="market_category"), nullable=True)
    )
    op.drop_constraint("houses_name_key", "houses", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("houses_name_key", "houses", ["name"])
    op.drop_column("houses", "market")
    # ### end Alembic commands ###
