"""empty message

Revision ID: 4efbf99522b3
Revises: 
Create Date: 2022-02-03 12:18:46.696774

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4efbf99522b3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("houses", "area", existing_type=postgresql.DOUBLE_PRECISION(precision=53), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("houses", "area", existing_type=postgresql.DOUBLE_PRECISION(precision=53), nullable=False)
    # ### end Alembic commands ###
