"""empty message

Revision ID: a3305e360b39
Revises: 4efbf99522b3
Create Date: 2022-02-03 12:32:18.315849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3305e360b39'
down_revision = '4efbf99522b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'houses', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'houses', type_='unique')
    # ### end Alembic commands ###
