"""empty message

Revision ID: a505324c6ac7
Revises: 89f4c2e4dd0d
Create Date: 2022-02-13 20:40:06.271944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a505324c6ac7'
down_revision = '89f4c2e4dd0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('houses_name_key', 'houses', type_='unique')
    op.create_unique_constraint(None, 'houses', ['name', 'website'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'houses', type_='unique')
    op.create_unique_constraint('houses_name_key', 'houses', ['name'])
    # ### end Alembic commands ###
