"""empty message

Revision ID: b0d0e6b36981
Revises: a3305e360b39
Create Date: 2022-02-04 10:30:22.823908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d0e6b36981'
down_revision = 'a3305e360b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('houses_name_key', 'houses', type_='unique')
    op.drop_constraint('houses_name_key1', 'houses', type_='unique')
    op.create_unique_constraint(None, 'houses', ['name', 'datetime'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'houses', type_='unique')
    op.create_unique_constraint('houses_name_key1', 'houses', ['name'])
    op.create_unique_constraint('houses_name_key', 'houses', ['name'])
    # ### end Alembic commands ###
